name: Java CI with Gradle

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Verify gradlew Exists
      run: ls -l gradlew || echo "gradlew not found!"

    - name: Grant Execute Permission
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Debug Build Output
      run: ls -l build/libs || echo "build/libs not found!"

    - name: Build Docker Image
      run: docker build -t docker.io/rajvanshidhruv/github_actions:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push docker.io/rajvanshidhruv/github_actions:latest
